### ISSUE TITLE
Tabbar improvements in TODO

### ISSUE THREAD

**Issue by pejakm** [QupZilla/qupzilla#1347]
- [ ] #1235 _Customizable tabbar positioning_
- [ ] #1238 _Tab grouping_
- [x] #1221 _Min and max tab width_
- [ ] #1128 _LRU tab switching order_
- [ ] #1382 _Double click to close tab_
- [ ] _Bottom tabs option_

**Comment by nowrep** [comment]
678b513820f57fbfc75fcb6facf34020f6e70733 Min and max tab width
