### ISSUE TITLE
Download manager improvements in TODO

### ISSUE THREAD

**Issue by pejakm** [QupZilla/qupzilla#1348]
- [ ] #884 _Download manager in new tab_
- [ ] #1244 _Pause/resume download_
- [ ] #992 _List of downloaded files_
- [ ] #32 _"Open with" menu action in file list_
- [ ] #1119 _Set origin URL file attribute to downloaded files_
