### ISSUE TITLE
Speed Dial improvements in TODO

### ISSUE THREAD

**Issue by pejakm** [QupZilla/qupzilla#1349]
- [x] #1345 _Improve for small screens_
- [ ] #1346 _Explicitly enable JS for image generator_
- [ ] #1207 _Dials custom image support_
- [ ] #1103 _Dials grouping support_
- [ ] #1104 _Opera like_ **_stash**_ _for speed dial_
- [x] #1360 _Enable smaller size for dials_
