### ISSUE TITLE
macOS, TODO: some issues

### ISSUE THREAD

**Issue by srazi** [QupZilla/qupzilla#2261]
- [ ] Global menu doesn't work correctly for more than one window. (indeed a regression since I fixed it some years ago)
- [x] (Probably fixed by 1d0d555ed11483ad7470f71c4a7d257044c94e36) Spell check does not work:
~~QtWebEngine dictionaries bundled with `QtWebEngineCore.Framework` are `pak` files that are not considered by QupZilla but also renaming them to `*.bdic` doesn't work (QupZilla doesn't load them).~~ When I use `bdic` dictionaries ~~instead `pak` files~~ then QupZilla loads them and I can enable spellcheck but yet spellcheck doesn't work on web pages.
- [x] (fixed by 1d0d555ed11483ad7470f71c4a7d257044c94e36) QupZilla looks for QtWebEngine dictionaries in some sub-directories of `QupZilla.app/Contents/Contents/` instead of `QupZilla.app/Contents/`
- [x] (fixed by 9af542aa03402eaa8b595b356871ae61c47522c7) `View->Show Tab Bar` should be removed: [solution](https://www.mail-archive.com/interest@qt-project.org/msg23593.html)

**Comment by nowrep** [comment]
Those `pak` files are QtWebEngine translations, not dictionaries.

**Comment by srazi** [comment]
Oops... my bad. Yeah they are placed in `qtwebengine_locales`. I should be blind.

**Comment by srazi** [comment]
With the current git spellcheck works correctly so maybe it was fixed by 1d0d555ed11483ad7470f71c4a7d257044c94e36

**Comment by Martii** [comment]
> Maybe we should bundle dictionaries with DMG file...

A minimum of at least one language to start would be great for testing usually.

<img src="https://cloud.githubusercontent.com/assets/114709/24087187/78f6401a-0ce1-11e7-8335-09423d762a6a.png" alt="Spellcheck before dictionaries" title="Click to enlarge" width="160" height="90" />

Didn't even realize I had to do some conversion until looked at that preferences page with https://github.com/QupZilla/qupzilla/wiki/Spell-Check linkage.

**Comment by Martii** [comment]
@srazi 
Btw if you need some ideas on what else to do with Mac issues... I can add a few to your list. Still trying to find time to work in everything and speed up compiling *(which happened today)* on the Mac... but don't want to overwhelm or overstep.

**Comment by srazi** [comment]
> Didn't even realize I had to do some conversion until looked at that preferences page with...

In appveyor script I used this [archive](http://chromium.googlesource.com/chromium/deps/hunspell_dictionaries/+archive/master.tar.gz) that contains both format `dic` and `bdic`.

> Btw if you need some ideas on what else to do with Mac issues... 

Good. Maybe I have not enough free time to work on them but at least a known issue is better than an unknown issue. ;)
