### ISSUE TITLE
All bookmarks improvements in TODO

### ISSUE THREAD

**Issue by nowrep** [QupZilla/qupzilla#458]
There is currently too many issues about some bookmark improvement, so I decided to sum it up in one single issue.
- [x] #17 ~~_Integration with Nepomuk_~~ - support for saving bookmarks via Nepomuk service on KDE (not really important, will not be implemented by @nowrep)
- [x] #398 ~~_Put "Most visited" folder in bookmark menu_~~ - give user option where to show Most Visited folder (Most Visited folder is no longer in bookmarks, only in History menu)
- [x] #445 ~~_Support for multi-level folders_~~
- [x] #446 ~~_URL keywords in bookmarks_~~ - support for setting shortcuts/nicks for bookmarks
- [x] #1087 ~~_Re-ordering bookmarks_~~ - support for re-ordering bookmarks
- [x] #1019 ~~_Expand/collapse in bookmarks sidebar_~~ - Option to toggle expanded/collapsed view in Bookmarks sidebar
- [ ] #1062 **Dropdown in bookmakrs toolbar** - Show dropdown menu when bookmarks don't fit in toolbar
- [x] #117 ~~_Sorting of bookmarks_~~ - sorting bookmarks by name, url, ... (implemented in 9f376ac14c93b676d6038c1cea9b6414b363b6f7)
- [x] #115 ~~_Drag&Drop support for sorting bookmarks_~~ (implemented in d9ae633d1a870cb9cdb7849234e4eeb5a9167269)
- [x] #351 ~~_Exporting bookmarks_~~ - support for exporting bookmarks in .html format (implemented in b1da23ca72fce0713c22630771eb0e917231446d)

If you have any other suggestions regarding bookmarks, please write it there.
I am planning to completely rewrite bookmarks backend with all these features in mind.

**Comment by CyberKiller40** [comment]
I can't find the bookmarks sorting anywhere in the current version 1.8.6 - I have loads of imported bookmarks and want to auto sort them alphabetically and recursively (cause they are in subdirectories too)
